name: DaylightSensorExpanded
version: 0.3
description: This allows you to change the values of the redstone signal strength of a Daylight Sensor. 
             See www.minecraftwiki.net/wiki/Daylight_Sensor
             Normally the values are from 0 to 15, you can re-map these 16 values to any other values you want.
             Example 15,14,13,12,10,9,8,7,6,5,4,3,2,1,0 would inverse the sensor.
             Example 1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0 would be good for a street lamp to turn on at sunset and off at sunrise.    
author: The_Nut
website: https://github.com/TheNut/DayLightSensorExpanded
main: ws.kristensen.DaylightSensorExpanded.DaylightSensorExpanded

commands:
  daylightsensorexpanded:
    description: Flag that the next sensor clicked on will be set to the given profile. If no profile is specified, 'default' profile will be assumed.
    aliases: dse
    permission: daylightsensorexpanded
    usage: /<command> set [profile]
  dseprofilecreate:
    description: Create a profile that can be applied to different Daylight Sensors.
    aliases: [daylightsensorexpandedprofilecreate, dsepcreate, dsepc]
    permission: daylightsensorexpanded.profile.create
    usage: /<command> [name] [parameters]
           /dsepcreate standard 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  dseprofilealter:
    description: Alter a profile by assigning new settings to it. This will affect ALL sensors assigned the profile name.
    aliases: [daylightsensorexpandedprofilealter, dsepalter, dsepa]
    permission: daylightsensorexpanded.profile.alter
    usage: /<command> [name] [parameters]
           /dsepalter standard 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  dseprofiledelete:
    description: Remove a profile that has been created.
    aliases: [daylightsensorexpandedprofiledelete, dsepdelete, dsepd]
    permission: daylightsensorexpanded.profile.delete
    usage: /<command> [name]
  dseprofilelist:
    description: Show a list of profile names that are defined.
    aliases: [daylightsensorexpandedprofilelist, dseplist, dsepl]
    permission: daylightsensorexpanded.profile.list
    usage: /<command>
  dsesensorset:
    description: Indicate that the next object clicked on will be a sensor and set to the given profile.
    aliases: [daylightsensorexpandedsensorset, dseset, dses]
    permission: daylightsensorexpanded.sensor.set
    usage: /<command> [profile name]
  dsesensorsetall:
    description: Indicate that all future Daylight Sensors placed by the user will be set to the given profile.
    aliases: [daylightsensorexpandedsensorsetall, dsesetall, dsesall, dsesa]
    permission: daylightsensorexpanded.sensor.setall
    usage: /<command> [profile name]
  dsesensorconvertall:
    description: Convert all sensors within a block radius to a given profile. Default of 50 radius from player location.
    aliases: [daylightsensorexpandedsensorconvertall, dseconvertall, dsecall, dseca]
    permission: daylightsensorexpanded.sensor.convert.all
    usage: /<command> [profile name] [optional radius]
  dsesensorclear:
    description: Indicate that the next object clicked on will be a sensor and will have the extended profile removed.
    aliases: [daylightsensorexpandedsensorclear, dseclear, dsesclear,  dsesc]
    permission: daylightsensorexpanded.sensor.clear
    usage: /<command>
  dsesensorlist:
    description: List all sensors that are considered extended sensors.
    aliases: [daylightsensorexpandedsensorlist, dselist, dseslist, dsesl]
    permission: daylightsensorexpanded.sensor.list
    usage: /<command>
  dsesensorinfo:
    description: Display the profile information for a sensor.
    aliases: [daylightsensorexpandedsensorinfo, dseinfo, dsesinfo, dsesi]
    permission: daylightsensorexpanded.sensor.info
    usage: /<command>
