name: DaylightSensorExpanded
version: 0.2
description: This allows you to change the values of the redstone signal strength of a Daylight Sensor. 
             See www.minecraftwiki.net/wiki/Daylight_Sensor
             Normally the values are from 0 to 15, you can re-map these 16 values to any other values you want.
             Example 15,14,13,12,10,9,8,7,6,5,4,3,2,1,0 would inverse the sensor.
             Example 1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0 would be good for a street lamp to turn on at sunset and off at sunrise.    
main: ws.kristensen.DaylightSensorExpanded.DaylightSensorExpanded
authors:
  - The_Nut

commands:
  daylightsensorexpanded:
    description: Flag that the next sensor clicked on will be set to the given profile. If no profile is specified, 'default' profile will be assumed.
    usage: /<command> set [profile]
    aliases: ['dse']
  dseprofilecreate:
    description: Create a profile that can be applied to different Daylight Sensors.
    usage: /<command> [name] [parameters]
    permission: daylightsensorexpanded.profile.create
    example: dsepcreate standard 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
    aliases: ['dsepcreate', 'dsepc']
  dseprofilealter:
    description: Alter a profile by assigning new settings to it. This will affect ALL sensors assigned the profile name.
    usage: /<command> [name] [parameters]
    permission: daylightsensorexpanded.profile.alter
    example: dsepalter standard 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
    aliases: ['dsepalter', 'dsepa']
  dseprofiledelete:
    description: Remove a profile that has been created.
    usage: /<command> [name]
    permission: daylightsensorexpanded.profile.delete
    aliases: ['dsepdelete', 'dsepd']
  dseprofilelist:
    description: Show a list of profile names that are defined.
    usage: /<command>
    permission: daylightsensorexpanded.profile.list
    aliases: ['dseplist', 'dsepl']
  dsesensorset:
    description: Indicate that the next object clicked on will be a sensor and set to the given profile.
    usage: /<command> [profile name]
    permission: daylightsensorexpanded.sensor.set
    aliases: ['dseset','dses']
  dsesensorsetall:
    description: Indicate that all future Daylight Sensors placed will be set to the given profile.
    usage: /<command> [profile name]
    permission: daylightsensorexpanded.sensor.setall
    aliases: ['dsesetall','dsesall', 'dsesa']
  dsesensorclear:
    description: Indicate that the next object clicked on will be a sensor and will have the extended profile removed.
    usage: /<command>
    permission: daylightsensorexpanded.sensor.clear
    aliases: ['dseclear','dsesclear', 'dsesc']
  dsesensorlist:
    description: List all sensors that are considered extended sensors.
    usage: /<command>
    permission: daylightsensorexpanded.sensor.list
    aliases: ['dselist','dseslist', 'dsesl']
  dsesensorconvertall:
    description: Convert all sensors within a block radius to a given profile. Default of 50 radius from player location.
    usage: /<command> [profile name] [optional radius]
    permission: daylightsensorexpanded.sensor.convert.all
    aliases: ['dseconvertall','dsecall', 'dseca']